jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@master
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        version: 1.8
    - continue-on-error: true
      name: Build with Maven
      run: mvn clean package -Dmaven.test.skip --file pom.xml
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
